### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by sundowndev** [erikvullings/strapi-to-typescript#31]
command: `sts ./api` 

```
TypeError: Cannot read property 'name' of undefined
    at /home/sundowndev/.nvm/versions/node/v12.18.3/lib/node_modules/strapi-to-typescript/dist/importer.js:116:61
    at Array.map (<anonymous>)
    at /home/sundowndev/.nvm/versions/node/v12.18.3/lib/node_modules/strapi-to-typescript/dist/importer.js:116:45
    at Array.forEach (<anonymous>)
    at /home/sundowndev/.nvm/versions/node/v12.18.3/lib/node_modules/strapi-to-typescript/dist/importer.js:110:11
    at new Promise (<anonymous>)
    at Object.importFiles (/home/sundowndev/.nvm/versions/node/v12.18.3/lib/node_modules/strapi-to-typescript/dist/importer.js:108:58)
    at /home/sundowndev/.nvm/versions/node/v12.18.3/lib/node_modules/strapi-to-typescript/dist/processor.js:20:45
    at Generator.next (<anonymous>)
    at fulfilled (/home/sundowndev/.nvm/versions/node/v12.18.3/lib/node_modules/strapi-to-typescript/dist/processor.js:5:58)
```

content of api folder : 

```
api         config      favicon.ico     migrations    public     tests           yarn.lock
build       Dockerfile  jest.config.js  node_modules  README.md  types
components  extensions  knexfile.js     package.json  seeds   
```

- node v12.18.3
- strapi v3.5.4

**Comment by aperron** [comment]
strange.

Your api folder need content `*.settings.json` file.  In these files, you must have: 

```json
{
  "info": {
    "name": "myname"
  },
  "//": "..."
}
``
